!
! Evaluation of the integrals on multigrid structure generated by uniform grid
!
! Chapter III, Section 2
!
! File: RMT_3D_2020_Example_09_M.f90
! File: RMT_3D_2020_Example_09_1.f90
! File: RMT_3D_2020_Example_09_2.f90
!    
program RMT_3D_2020_Example_09_M
USE     RMT_3D_2020_Example_09_1                                   ! 001
USE     RMT_3D_2020_Example_09_2                                   ! 002
USE     RMT_3D_2020                                                ! 003
USE     RMT_3D_UFG                                                 ! 004

            NXX_FG = 250; N_coarsest_X = 1; LevelXd = 0; a_ = 1.d0 ! 005  
            NYY_FG = 250; N_coarsest_Y = 1; LevelYd = 0; b_ = 1.d0 ! 006
            NZZ_FG = 250; N_coarsest_Z = 1; LevelZd = 0; c_ = 1.d0 ! 007
 
            call MSSize                                                
            call U_Finest_Grid(1,1,1)  
            call Coarse_Grids('+')                                      
            call Copy_Grid     
  
 open(1,file='RMT_3D_2020_Example_09.res')

    do      LevelC =                           LevelM,0,-1
            LevelX = min(LeXmax              , LevelC)
            LevelY = min(       LeYmax       , LevelC)
            LevelZ = min(              LeZmax, LevelC)
                                               call Matrix_and_Vector
     do     GridsX = 1,3**LevelX;              call Index_Mapping('-',1)	
      do    GridsY = 1,3**LevelY;              call Index_Mapping('-',2)
       do   GridsZ = 1,3**LevelZ;              call Index_Mapping('-',3)
                                               call Vanka_type_Smoother
       end do                                      
      end do
     end do
    end do
 close(1)  
 
end program RMT_3D_2020_Example_09_M
