!
! Numerical solution of model BVP on multigrid structure generated by uniform grid
! Smoother is point Seidel iterations
!
! Chapter III, Section 4
!
! File: RMT_3D_2020_Example_12_M.f90
! File: RMT_3D_2020_Example_12_1.f90
! File: RMT_3D_2020_Example_12_2.f90
!    
program RMT_3D_2020_Example_12_M
USE     RMT_3D_2020_Example_12_1                                               
USE     RMT_3D_2020_Example_12_2                                            
USE     RMT_3D_2020                                                     ! 001   
USE     RMT_3D_UFG                                                      ! 002

 NXX_FG = 250; N_coarsest_X = 5; LevelXd = 0; a_ = 0.9d0                ! 003  
 NYY_FG = 250; N_coarsest_Y = 5; LevelYd = 0; b_ = 0.9d0                ! 004
 NZZ_FG = 250; N_coarsest_Z = 5; LevelZd = 0; c_ = 0.9d0                ! 005
 
  q_max = 15; NSIL = 8; ResLIM = 1.e-6                                  ! 006 

            call MSSize                                                 ! 007 
            call U_Finest_Grid(1,1,1)                                   ! 008
            call Coarse_Grids('+')                                      ! 009
            call Copy_Grid                                              ! 010
  
 allocate(    hatU(0:NXX_FG+2,0:NYY_FG+2,0:NZZ_FG+2), &                 ! 011  
              corU(0:NXX_FG+2,0:NYY_FG+2,0:NZZ_FG+2), &                 ! 011  
              RHSF(0:NXX_FG+2,0:NYY_FG+2,0:NZZ_FG+2), &                 ! 011  
          Lambda_X(0:NXX_FG+2,0:NYY_FG+2,0:NZZ_FG+2), &                 ! 011  			 
          Lambda_Y(0:NXX_FG+2,0:NYY_FG+2,0:NZZ_FG+2), &                 ! 011  
          Lambda_Z(0:NXX_FG+2,0:NYY_FG+2,0:NZZ_FG+2), &                 ! 011  
             L_A_X(0:NXX_FG+2,0:NYY_FG+2,0:NZZ_FG+2), &                 ! 011  			 
             L_A_Y(0:NXX_FG+2,0:NYY_FG+2,0:NZZ_FG+2), &                 ! 011  
             L_A_Z(0:NXX_FG+2,0:NYY_FG+2,0:NZZ_FG+2)  )                 ! 011  
   
 allocate(  BC_0YZ(           0:NYY_FG+2,0:NZZ_FG+2), &                 ! 012
            BC_1YZ(           0:NYY_FG+2,0:NZZ_FG+2), &                 ! 012 
            BC_X0Z(0:NXX_FG+2,           0:NZZ_FG+2), &                 ! 012
            BC_X1Z(0:NXX_FG+2,           0:NZZ_FG+2), &                 ! 012
            BC_XY0(0:NXX_FG+2,0:NYY_FG+2           ), &                 ! 012
            BC_XY1(0:NXX_FG+2,0:NYY_FG+2           )  )                 ! 012
 
 open(1,file='RMT_3D_2020_Example_12.res')
 
            call Starting_Guess_and_Boundary_Conditions                 ! 013

   do            q = 1,q_max                                            ! 014 
    do      LevelC =                           LevelM,0,-1
            LevelX = min(LeXmax              , LevelC)
            LevelY = min(       LeYmax       , LevelC)
            LevelZ = min(              LeZmax, LevelC)
                                               call Matrix_and_Vector
     do     GridsX = 1,3**LevelX;              call Index_Mapping('-',1)
      do    GridsY = 1,3**LevelY;              call Index_Mapping('-',2)
       do   GridsZ = 1,3**LevelZ;              call Index_Mapping('-',3)
                                               call point_Seidel_Smoother
       end do
      end do
     end do
    end do
                                               call Convergence_Test    ! 015
            if(ResMAX/Res_000<ResLIM) exit                              ! 016   
   end do                                                               ! 017
   
   AresR =(ResMAX/Res_000)**(1.D0/dfloat(q))                            ! 018 
   write(*,1) AresR; write(1,1) AresR                                   ! 019 
   close(1)                                                             ! 020
   deallocate(hatU,corU,RHSF,Lambda_X,Lambda_Y,Lambda_Z,L_A_X,L_A_Y,L_A_Z)
   deallocate(BC_0YZ,BC_1YZ,BC_X0Z,BC_X1Z,BC_XY0,BC_XY1)
1 format(/17x,'AresR = ',F5.3/)   
end program RMT_3D_2020_Example_12_M
