name: Fortran CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Fortran-CI:
    name: ubuntu-20.04
    
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install gfortran

    - name: Build shared modules
      run: |
        gfortran -O3 RMT_3D_NFG.f90 -lRMT_3D_2020 -IRMT_Linux_x86_64 -LRMT_Linux_x86_64 -c -o RMT_3D_NFG.o        
        gfortran -O3 RMT_3D_NFG2.f90 -lRMT_3D_2020 -IRMT_Linux_x86_64 -LRMT_Linux_x86_64 -c -o RMT_3D_NFG2.o
        gfortran -O3 RMT_3D_UFG.f90 -lRMT_3D_2020 -IRMT_Linux_x86_64 -LRMT_Linux_x86_64 -c -o RMT_3D_UFG.o
        
    - name: Build and run example 01
      run: |
        gfortran -O3 RMT_3D_2020_Example_01/RMT_3D_2020_Example_01.f90 -o RMT_3D_2020_Example_01/RMT_3D_2020_Example_01
        RMT_3D_2020_Example_01/RMT_3D_2020_Example_01
        
    - name: Build and run example 02
      run: |
        gfortran -O3 RMT_3D_2020_Example_02/RMT_3D_2020_Example_02_1.f90 -c -o RMT_3D_2020_Example_02_1.o
        gfortran -O3 RMT_3D_2020_Example_02/RMT_3D_2020_Example_02_2.f90 -c -o RMT_3D_2020_Example_02_2.o
        gfortran -O3 RMT_3D_2020_Example_02/RMT_3D_2020_Example_02_M.f90 RMT_3D_2020_Example_02_1.o RMT_3D_2020_Example_02_2.o -o RMT_3D_2020_Example_02/RMT_3D_2020_Example_02_M
        RMT_3D_2020_Example_02/RMT_3D_2020_Example_02_M
